### ISSUE TITLE
Error starting or running tests

### ISSUE THREAD

**Issue by mikeerickson** [samuxyz/bookstore#1]
Please see the following console output:

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/mikeerickson/.nvm/versions/node/v6.3.1/bin/node" "/Users/mikeerickson/.nvm/versions/node/v6.3.1/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bookstore@1.0.0 start: `SET NODE_ENV=dev && node server.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the bookstore@1.0.0 start script 'SET NODE_ENV=dev && node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bookstore package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     SET NODE_ENV=dev && node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bookstore
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bookstore
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mikeerickson/Documents/Projects/node/bookstore/npm-debug.log
 ✘  ~/Documents/Projects/node/bookstore  master 
 $ node -v
v6.3.1
 ~/Documents/Projects/node/bookstore  master 
 $
```

**Comment by jyotirmaybanerjee** [comment]
It works for me after switching to node 6. And don't forget to change the mongodb URIs in all three config files.

**Comment by samuxyz** [comment]
Yes exactly, as stated in the tutorial, it requires node 6 or you can add babel to the package.json!

**Comment by AlexMurphy** [comment]
I've encountered the same issue using v6.0.0 & v6.10.1, is there a specific version I should be using?

**Comment by speaud** [comment]
I'm using v6.12.0 without any issues

**Comment by hieutle2011** [comment]
I have updated mongodb URIs in all 3 config files, but still have issues as below.

0 info it worked if it ends with ok
1 verbose cli [ '/home/kbankuser/.nvm/versions/node/v9.3.0/bin/node',
1 verbose cli   '/home/kbankuser/.nvm/versions/node/v9.3.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v9.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bookstore@1.0.0~prestart: bookstore@1.0.0
6 info lifecycle bookstore@1.0.0~start: bookstore@1.0.0
7 verbose lifecycle bookstore@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle bookstore@1.0.0~start: PATH: /home/kbankuser/.nvm/versions/node/v9.3.0/lib/node_modules/npm/bin/node-gyp-bin:/home/kbankuser/Documents/Personal/bookstore/node_modules/.bin:/home/kbankuser/.nvm/versions/node/v9.3.0/bin:/home/kbankuser/bin:/home/kbankuser/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle bookstore@1.0.0~start: CWD: /home/kbankuser/Documents/Personal/bookstore
10 silly lifecycle bookstore@1.0.0~start: Args: [ '-c', 'SET NODE_ENV=dev && node server.js' ]
11 info lifecycle bookstore@1.0.0~start: Failed to exec start script
12 verbose stack Error: bookstore@1.0.0 start: `SET NODE_ENV=dev && node server.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/home/kbankuser/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:159:13)
12 verbose stack     at maybeClose (internal/child_process.js:943:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
13 verbose pkgid bookstore@1.0.0
14 verbose cwd /home/kbankuser/Documents/Personal/bookstore
15 verbose Linux 4.15.0-39-generic
16 verbose argv "/home/kbankuser/.nvm/versions/node/v9.3.0/bin/node" "/home/kbankuser/.nvm/versions/node/v9.3.0/bin/npm" "start"
17 verbose node v9.3.0
18 verbose npm  v5.5.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error bookstore@1.0.0 start: `SET NODE_ENV=dev && node server.js`
23 error spawn ENOENT
24 error Failed at the bookstore@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
